CREATE DATABASE IF NOT EXISTS OWLFLIX_DB;

USE OWLFLIX_DB;

-- ----------------------------------------------------------------------------- --
CREATE TABLE USUARIO (
    ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWD VARCHAR(255) NOT NULL, -- HASH
    ES_ADMIN BOOLEAN DEFAULT FALSE,
    PRIMARY KEY(ID)
);

SELECT * FROM USUARIO;

INSERT INTO USUARIO (NOMBRE, APELLIDO, EMAIL, PASSWD, ES_ADMIN) VALUES 
('Gabito', 'FerWais', 'gaboAdmin@admin.com', '$2a$10$5Qqy12.PIWq9TsA17wd1HuHpj.aJ3ToDOF6h6QNi/BI0pMouQfB1e', 1),
('Monet', 'PozoMonet', 'marianAdmin@admin.com', '$2a$10$M810JYRlA79K94BT.QWawe2F282FtNI8h41F3TMfYeSe5n7dNNerO', 1);

DROP TABLE USUARIO;

CREATE TABLE GENERO (
    ID INT AUTO_INCREMENT,
    ID_GEN INT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    PRIMARY KEY (ID)
);

DROP TABLE GENERO;

CREATE TABLE PELICULAS_SERIES (
    ID_PS INT AUTO_INCREMENT,
    TITULO_PS VARCHAR(100) NOT NULL,
    URL_IMAGEN VARCHAR(255) NOT NULL,
    CATEGORIA ENUM('PELICULA', 'SERIE') NOT NULL,
    SINOPSIS TEXT,
    FECHA_LANZAMIENTO DATE,
    TEMPORADAS INT,
    PRIMARY KEY(ID_PS)
);

SELECT * FROM PELICULAS_SERIES;

DROP TABLE PELICULAS_SERIES;

CREATE TABLE GENEROS_PELICULAS_SERIES (
    ID_PS INT NOT NULL,
    ID_GENERO INT NOT NULL,
    PRIMARY KEY(ID_PS, ID_GENERO),
    FOREIGN KEY (ID_PS) REFERENCES PELICULAS_SERIES(ID_PS),
    FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID)
);

SELECT * FROM GENEROS_PELICULAS_SERIES;

DROP TABLE GENEROS_PELICULAS_SERIES;

CREATE TABLE CARRITO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    PS_ID INT NOT NULL,
    PRECIO DECIMAL(10, 2) DEFAULT 1000,
    CANTIDAD INT DEFAULT 1,
    FECHA_INGRESADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
    FOREIGN KEY (PS_ID) REFERENCES PELICULAS_SERIES(ID_PS),
    UNIQUE (USUARIO_ID, PS_ID)
);

SELECT * FROM CARRITO;

DROP TABLE CARRITO;
